version: 0.2

phases:
  pre_build:
    commands:
      - ls -la
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files: 
      - imagedefinitions.json
      - imagedefinitions2.json

